---
# Source: enforcer/templates/enforcer-token-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: aqua-agent-token
  namespace: aqua
  labels:
    app: aqua-ds
    aqua.component: enforcer
    helm.sh/chart: 'enforcer-2022.4.28'
    app.kubernetes.io/name: "enforcer"
    app.kubernetes.io/instance: mc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "2022.4"
type: Opaque
data:
  token: blah
