apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - enforcer-configmap.yaml
  - enforcer-daemonset.yaml
  - enforcer-token-secret.yaml
  - rbac.yaml
  - serviceaccount.yaml
