---
# Source: enforcer/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aqua-cluster-role
  labels:
    app: aqua-ds
    aqua.component: enforcer
    helm.sh/chart: 'enforcer-2022.4.28'
    app.kubernetes.io/name: "enforcer"
    app.kubernetes.io/instance: mc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "2022.4"
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
- apiGroups: [""]
  resources: ["nodes", "services", "endpoints", "pods", "deployments", "namespaces","componentstatuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
# Source: enforcer/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aqua-role-binding
  namespace: aqua
  labels:
    app: aqua-ds
    aqua.component: enforcer
    helm.sh/chart: 'enforcer-2022.4.28'
    app.kubernetes.io/name: "enforcer"
    app.kubernetes.io/instance: mc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "2022.4"
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: aqua-cluster-role
subjects:
  - kind: ServiceAccount
    name: aquasvc
    namespace: aqua
---
# Source: enforcer/templates/rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aqua-rolebinding-vmware-system-privileged
  namespace: aqua
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
---
# Source: enforcer/templates/rbac.yaml
## Openshift RBAC

## TKG RBAC
