---
# Source: enforcer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aquasvc
  namespace: aqua
  labels:
    app: aqua-ds
    aqua.component: enforcer
    helm.sh/chart: 'enforcer-2022.4.28'
    app.kubernetes.io/name: "enforcer"
    app.kubernetes.io/instance: mc
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "2022.4"
imagePullSecrets:
- name: 
